// <auto-generated />
using System;
using AsadaSJM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AsadaSJM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AsadaSJM.Models.Abonado", b =>
                {
                    b.Property<int>("IdAbonado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAbonado"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NumeroMedidor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdAbonado");

                    b.ToTable("Abonados");

                    b.HasData(
                        new
                        {
                            IdAbonado = 1,
                            Activo = true,
                            Direccion = "Calle Los Robles",
                            Nombre = "María Vargas",
                            NumeroMedidor = "MED-0231"
                        },
                        new
                        {
                            IdAbonado = 2,
                            Activo = true,
                            Direccion = "Barrio Central",
                            Nombre = "Juan Rojas",
                            NumeroMedidor = "MED-0198"
                        },
                        new
                        {
                            IdAbonado = 3,
                            Activo = false,
                            Direccion = "Calle La Montaña",
                            Nombre = "Lucía Solano",
                            NumeroMedidor = "MED-0177"
                        });
                });

            modelBuilder.Entity("AsadaSJM.Models.Averia", b =>
                {
                    b.Property<int>("IdAveria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAveria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAbonado")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdAveria");

                    b.HasIndex("IdAbonado");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Averias");

                    b.HasData(
                        new
                        {
                            IdAveria = 1,
                            Descripcion = "Fuga en tubería principal",
                            Estado = "Pendiente",
                            FechaReporte = new DateTime(2026, 9, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAbonado = 1
                        },
                        new
                        {
                            IdAveria = 2,
                            Descripcion = "Baja presión de agua",
                            Estado = "En proceso",
                            FechaReporte = new DateTime(2026, 9, 2, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IdAbonado = 2,
                            IdUsuario = 2
                        },
                        new
                        {
                            IdAveria = 3,
                            Descripcion = "Medidor dañado",
                            Estado = "Resuelto",
                            FechaReporte = new DateTime(2026, 9, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAbonado = 3,
                            IdUsuario = 2
                        });
                });

            modelBuilder.Entity("AsadaSJM.Models.Bitacora", b =>
                {
                    b.Property<int>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdBitacora");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("AsadaSJM.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdTramite")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdTramite");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("AsadaSJM.Models.Recibo", b =>
                {
                    b.Property<int>("IdRecibo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecibo"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAbonado")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdRecibo");

                    b.HasIndex("IdAbonado");

                    b.ToTable("Recibos");

                    b.HasData(
                        new
                        {
                            IdRecibo = 1,
                            FechaEmision = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAbonado = 1,
                            Monto = 6450m
                        },
                        new
                        {
                            IdRecibo = 2,
                            FechaEmision = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAbonado = 2,
                            Monto = 5120m
                        });
                });

            modelBuilder.Entity("AsadaSJM.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Operativo"
                        },
                        new
                        {
                            IdRol = 3,
                            NombreRol = "Abonado"
                        });
                });

            modelBuilder.Entity("AsadaSJM.Models.Tramite", b =>
                {
                    b.Property<int>("IdTramite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTramite"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAbonado")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TipoTramite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTramite");

                    b.HasIndex("IdAbonado");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tramites");

                    b.HasData(
                        new
                        {
                            IdTramite = 1,
                            Estado = "Pendiente",
                            FechaSolicitud = new DateTime(2026, 9, 1, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            IdAbonado = 1,
                            TipoTramite = "Cambio de titular"
                        },
                        new
                        {
                            IdTramite = 2,
                            Estado = "En revisión",
                            FechaSolicitud = new DateTime(2026, 9, 2, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAbonado = 2,
                            TipoTramite = "Solicitud de conexión"
                        },
                        new
                        {
                            IdTramite = 3,
                            Estado = "Aprobado",
                            FechaSolicitud = new DateTime(2026, 9, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            IdAbonado = 3,
                            TipoTramite = "Reclamo de facturación"
                        });
                });

            modelBuilder.Entity("AsadaSJM.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Activo = true,
                            ContrasenaHash = "temporal",
                            Correo = "pjimenez@asadasjm.cr",
                            IdRol = 1,
                            Nombre = "P. Jiménez"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Activo = true,
                            ContrasenaHash = "temporal",
                            Correo = "cmora@asadasjm.cr",
                            IdRol = 2,
                            Nombre = "C. Mora"
                        });
                });

            modelBuilder.Entity("AsadaSJM.Models.Averia", b =>
                {
                    b.HasOne("AsadaSJM.Models.Abonado", "Abonado")
                        .WithMany("Averias")
                        .HasForeignKey("IdAbonado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsadaSJM.Models.Usuario", "Responsable")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Abonado");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("AsadaSJM.Models.Bitacora", b =>
                {
                    b.HasOne("AsadaSJM.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AsadaSJM.Models.Documento", b =>
                {
                    b.HasOne("AsadaSJM.Models.Tramite", "Tramite")
                        .WithMany("Documentos")
                        .HasForeignKey("IdTramite");

                    b.Navigation("Tramite");
                });

            modelBuilder.Entity("AsadaSJM.Models.Recibo", b =>
                {
                    b.HasOne("AsadaSJM.Models.Abonado", "Abonado")
                        .WithMany("Recibos")
                        .HasForeignKey("IdAbonado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonado");
                });

            modelBuilder.Entity("AsadaSJM.Models.Tramite", b =>
                {
                    b.HasOne("AsadaSJM.Models.Abonado", "Abonado")
                        .WithMany("Tramites")
                        .HasForeignKey("IdAbonado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AsadaSJM.Models.Usuario", "Gestor")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Abonado");

                    b.Navigation("Gestor");
                });

            modelBuilder.Entity("AsadaSJM.Models.Usuario", b =>
                {
                    b.HasOne("AsadaSJM.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AsadaSJM.Models.Abonado", b =>
                {
                    b.Navigation("Averias");

                    b.Navigation("Recibos");

                    b.Navigation("Tramites");
                });

            modelBuilder.Entity("AsadaSJM.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AsadaSJM.Models.Tramite", b =>
                {
                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
